apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    executionID: executionID
    pipelineID: pipelineID
    runID: run-executionid-0
    gogoowang: "true"
  name: expr-1629299870-trim-test
spec:
  serviceAccountName: default 
  pipelineSpec:
    tasks:
    - name: activatestageid22
      taskSpec:
        results:
          - name: 448a-9320sssss
        steps:
        - env:
          image: imrcrab/nop:0.6
          name: stgstep02
          script: |
            printf "#{option}" | tee $(results.448a-9320sssss.path)
            ls -all /tekton/results
            cat /tekton/results/448a-9320sssss
          workingDir: /workspace
        workspaces:
        - mountPath: /workspace
          name: shared-workspace
      workspaces:
      - name: shared-workspace
        workspace: shared-workspace
    workspaces:
    - name: shared-workspace
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: mmpvc
