apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    executionID: executionID
    pipelineID: pipelineID
    runID: run-executionID-0
  name: run-executionID-0
spec:
  pipelineSpec:
    resources:
    - name: clone-done
      type: git
    tasks:
    - name: activate-stage-ID1
      runAfter:
      - clone-repo
      taskSpec:
        steps:
        - command:
          - sh
          - -c
          - chmod 777 ${SHARED_WORKSPACE}
          env:
          - name: SHARED_WORKSPACE
            value: /workspace
          - name: WORKDIR
            value: repo
          image: pulse-line.tencentcloudcr.com/public/busybox
          name: stgstep-stage-ID1
          workingDir: /workspace/repo
        workspaces:
        - mountPath: /workspace
          name: shared-workspace
      workspaces:
      - name: shared-workspace
        workspace: shared-workspace
    - name: activate-stage-ID2
      runAfter:
      - job-ref-2
      taskSpec:
        steps:
        - env:
          - name: SHARED_WORKSPACE
            value: /workspace
          - name: WORKDIR
            value: repo
          image: pulse-line.tencentcloudcr.com/tekton/hang
          name: stgstep-stage-ID2
          workingDir: /workspace/repo
        workspaces:
        - mountPath: /workspace
          name: shared-workspace
      workspaces:
      - name: shared-workspace
        workspace: shared-workspace
    - name: clone-repo
      resources:
        inputs:
        - name: clone-done
          resource: clone-done
      taskSpec:
        resources:
          inputs:
          - name: clone-done
            targetPath: repo
            type: git
        steps:
        - command:
          - "true"
          env:
          - name: SHARED_WORKSPACE
            value: /workspace
          - name: WORKDIR
            value: repo
          image: pulse-line.tencentcloudcr.com/public/busybox
          name: clone-done
          workingDir: /workspace/repo
        workspaces:
        - mountPath: /workspace
          name: shared-workspace
      workspaces:
      - name: shared-workspace
        workspace: shared-workspace
    - name: job-ref-1
      runAfter:
      - activate-stage-ID1
      taskSpec:
        steps:
        - env:
          - name: SHARED_WORKSPACE
            value: /workspace
          - name: WORKDIR
            value: repo
          image: busybox
          name: step-id-1
          script: |
            #!/bin/sh
            ls-al
          workingDir: /workspace/repo
        workspaces:
        - mountPath: /workspace
          name: shared-workspace
      workspaces:
      - name: shared-workspace
        workspace: shared-workspace
    - name: job-ref-2
      runAfter:
      - job-ref-1
      taskSpec:
        steps:
        - args:
          - --dockerfile=repo/Dockerfile
          - --destination=docker.io/chuhongxin/test:latest
          - --context=dir://repo
          command:
          - /kaniko/executor
          env:
          - name: SHARED_WORKSPACE
            value: /workspace
          - name: WORKDIR
            value: repo
          image: gcr.io/kaniko-project/executor:latest
          name: step-id-2
          workingDir: /workspace/repo
        workspaces:
        - mountPath: /workspace
          name: shared-workspace
      workspaces:
      - name: shared-workspace
        workspace: shared-workspace
    - name: job-ref-3
      runAfter:
      - activate-stage-ID2
      taskSpec:
        steps:
        - env:
          - name: SHARED_WORKSPACE
            value: /workspace
          - name: WORKDIR
            value: repo
          image: busybox
          name: step-id-3
          script: |
            #!bin/sh
            ls-al
          workingDir: /workspace/repo
        workspaces:
        - mountPath: /workspace
          name: shared-workspace
      workspaces:
      - name: shared-workspace
        workspace: shared-workspace
    workspaces:
    - name: shared-workspace
  resources:
  - name: clone-done
    resourceSpec:
      params:
      - name: url
        value: https://github.com/chu159/Tekton.git
      - name: revision
        value: master
      type: git
  taskRunSpecs:
  - pipelineTaskName: clone-repo
    taskServiceAccountName: executionID-clone-repo
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: executionID

